[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'npm run build:ts',
  'cd client && npm install',
  'cd client && npm run build'
]

[start]
cmd = 'npm start'