[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm install',
  'cd client && npm install'
]

[phases.build]
cmds = [
  'npm run build:ts',
  'cd client && npm run build'
]

[start]
cmd = 'npm start'